### ISSUE TITLE
Windy shows incorrect icon?

### ISSUE THREAD

**Issue by bremor** [DavidFW1960/bom-weather-card#29]
G'day David, I have recently started using this card again.. which is amazing by the way.

Today and tomorrows icon code is "wind":
![image](https://user-images.githubusercontent.com/34525505/94876148-278da100-049a-11eb-9c88-67f638abd172.png)

Yet, the card is showing the icon for cloudy
![image](https://user-images.githubusercontent.com/34525505/94876237-6f142d00-049a-11eb-8444-23d4a695e96f.png)

**Comment by DavidFW1960** [comment]
That is correct if you are using the standard icons... there is no windy icon.
As long as you installed the latest icon files you can use the flag old_icon which defaults to true but can set to false or hybrid.

**Comment by DavidFW1960** [comment]
also see today's low is showing NaN? This means you have not configured the template sensors as well.
One other thing... in 0.116.x, they are changing a bunch of stuff and this card is broken in beta. Are you in a position to help me make it work again?

**Comment by bremor** [comment]
Awesome! 'hybrid' did the trick. Today's low is a work in progress, will get around to this soon.

Happy to lend a hand during the month of hacktober :)

**Comment by DavidFW1960** [comment]
> Today's low is a work in progress

It's in the sample templates. BOM does not publish the low after around 4am in the morning and the high from around 3pm so the statistics and template sensor fix that issue. 

Great re: the card...

It's crapping out here
```
  updateValues() {
    const root = this.shadowRoot;
    if (root.childElementCount > 0) {
```
line 878 as this.shadowRoot is not available and the card disappears completely.
Theres a lot of custom cards gone to shit with 0.116 due to changes in the way cards load. I think it's not too difficult.. probably... for a smart person who knows js (ie not me)

**Comment by DavidFW1960** [comment]
Any chance you can look at this Brendon now 0.116 is out?

**Comment by DavidFW1960** [comment]
Looks like Simon fixed it. All good now.
