### ISSUE TITLE
Suggestion: Support the ‘title’ attribute for the card 

### ISSUE THREAD

**Issue by sab-automation-oz** [DavidFW1960/bom-weather-card#36]
Allow the  ‘title’ attribute for the card to be presented in the UX for the card.

**Comment by DavidFW1960** [comment]
I don't think this is possible. None of the custom weather cards do this.

Have you considered using a markdown card? I use those for similar situations. I then also use card-mod to display it so it's consistent with other cards like this:
```
          - type: markdown
            style:
              ha-markdown:
                $: |
                  h1 {
                    display: block;
                    letter-spacing: -0.012em;
                    line-height: 32px;
                    font-size: 24px;
                    margin-block-start: 0.83em;
                    margin-block-end: 0.83em;
                    margin-inline-start: 0px;
                    margin-inline-end: 0px;
                    font-weight: normal;
                  }
            content: >
              # Tasmota Scripts
```
Use it in a vertical stack with the weather card
![image](https://user-images.githubusercontent.com/36390762/98177894-b08f7080-1f4f-11eb-9d39-144d388484a2.png)

I used to use h2 for this but it doesn't work anymore. So that's an example
