### ISSUE TITLE
Having trouble getting the icons to show up

### ISSUE THREAD

**Issue by quadhammer** [DavidFW1960/bom-weather-card#38]
I'm not sure if I'm just being impatient, and this is just a bit of a glitch with the new way of retrieving the BOM information, or if I've done something wrong.

As an example:
entity_current_conditions: sensor.australiansuburbname_mdi_icon_0 

which right now is supposed to display:
mdi:weather-sunny 

I have a sunny.png in \config\www\bom_icons
and I've tried              \config\www\icons\bom_icons

but nothing seems to be appearing.  Any ideas, please?

**Comment by DavidFW1960** [comment]
This card does not do mdi icons. It uses animated or static icons primarily using mag charts icons.
Current conditions uses a template sensor.
Please follow the docs.

**Comment by quadhammer** [comment]
>  Please follow the docs.
I'm trying! but I'm finding it difficult.  Thank you for your help.

The readme says "extract the contents to /config/www/bom_icons"

but your personal example, and the weather.yaml seems to have them under \config\www\icons\bom_icons

# Download the BOM icons from https://github.com/DavidFW1960/bom_forecast/blob/master/bom_icons.zip
# and save them under <config-dir>/www/icons/bom_icons/

"You can call template sensors whatever you want so long as you use the same name in the card config. (Included in weather.yaml)"

I've found the weather.yaml, by downloading the code, but where do I put it?  It wasn't installed that I can see with the HACS installation method.

Do I need to install template.md somewhere too after updating the entities?

Sorry if this seems obvious, but I would appreciate more help. Cheers!

**Comment by DavidFW1960** [comment]
There are 2 sets of icons. The bom_icons is for the basic card.

To use weather.yaml you need to be using packages.

The weather_icons.zip needs to go here
```
<config-dir>/www/icons/weather_icons/animated/

<config-dir>/www/icons/weather_icons/static/
```
Template.md has sample templates. I suggest using the package.

You need to be using packages in Home Assistant and drop the packages in the packages folder.
If you loot at my home-assistant repo in my configuration.yaml you can see exactly how to do that and can also see the weather package in the packages folder. You can also check my icons folders.

The icon part might be less than clear so I'll look at that doc tomorrow. I'm not on my PC right now ...

**Comment by quadhammer** [comment]
OK, thanks I'll try to copy your example.  I'm not familiar with packages, but I'll look them up.

As a side note it looks like sensor.gosford_wind_speed has changed to sensor.gosford_wind_speed_kilometre

Cheers

**Comment by DavidFW1960** [comment]
> As a side note it looks like sensor.gosford_wind_speed has changed to sensor.gosford_wind_speed_kilometre
> 
> and sensor.gosford_temperature seems to be sensor.gosford_temp

No they are unchanged here and working

**Comment by quadhammer** [comment]
Hmm, I'm using this: https://github.com/bremor/bureau_of_meteorology and my entities are a bit different to yours, besides the suburb/city names of course.

**Comment by DavidFW1960** [comment]
I use that integration as well

**Comment by DavidFW1960** [comment]
Seems a bunch of sensors got renamed in the last update.
I updated all the docs and hopefully made the directory structure clearer
Let me know if this is working for you now. (I did redo the package and templates as well for the new sensor names)

**Comment by quadhammer** [comment]
Okay, this is what I have tried so far to no avail:

Put contents of weather_icons.zip to config\www\icons\bom_icons

Make a directory called packages in the config directory
put the weather.yaml file in there

modify configuration.yaml to include the packages directory
`homeassistant:

  packages: !include_dir_named packages  `

Install the "average" integration from the HACS store

Add contents of template.md to configuration yaml… This seems like a guess step on my part, but I don't know where else to put it.

And of course, go through and change all the entity names to my suburb/city. It does get confusing though because a standard find and replace won't work because of some of the subtle renaming of entities generated by the BOM integration.

Edit: I see you've changed the names, so I will retry with that version, and thanks for the updates!

**Comment by DavidFW1960** [comment]
Check the updated docs for the icons as well. Also if you use the package don't worry about templates.md as they are already in the package.
I updated all the sensors for the new names so cut/paste should work.
Don't forget you need to add a card to lovelace as well.

**Comment by quadhammer** [comment]
I'm making headway now, thanks!  Must've been the new naming conventions, I think.  Animated icons for entity_current_conditions: sensor.suburbname_icon_descriptor_0....now for the rest. :)

**Comment by quadhammer** [comment]
All working now, thanks.  I removed the template.md section from my configuration.yaml, and after a reboot it still works.

These:
entity_daytime_high: sensor.bom_today_max
entity_daytime_low: sensor.bom_today_min
and bom_current_text are displaying as unavailable, but that's the BOM integration which isn't reporting anything with sensor.bom_* for some reason.

Thanks again for your help.  Hopefully my cluelessness will help others! :)

**Comment by quadhammer** [comment]
After deleting the old BOM ftp integration it can't find anything with sensor.bom_* , (naturally), so in the example card

entity_daytime_high: sensor.bom_today_max I'm guessing should be entity_daytime_high: sensor.suburbname_temp_max_0 ?

**Comment by DavidFW1960** [comment]
Those are ALL template sensors in the package

**Comment by quadhammer** [comment]
D'oh, must've missed a step.  Thanks for your patience.

**Comment by DavidFW1960** [comment]
_0 is today so sensor.suburbname_fire_danger_0 is correct. Check in dev_tools that that sensor exists. Some of those entities might get blanked out by BOM (~10PM perhaps)

**Comment by DavidFW1960** [comment]
my fire_danger_0 is saying unknown as well today.... BOM shits the bed with this sometimes.

**Comment by itsslamdunx** [comment]
Hi David

Beautiful looking package. However like Quadhammer I've found this pretty tough to get going and still no luck. 

A short bullet-point of steps to install at the top of the repo would save users much time. I've done one below if that helps your users.

I've almost got it going but just can't load values for sensors that HA tells me exist from  bremor / bureau_of_meteorology  so I guess I'm stuck at step 10. For now I'm just trying to get the smaller version going as the full card doesn't load anything at all. You can see from the screen grabs I'm trying to troubleshoot forecast _short_text_ which exist but don't get loaded. 

Any thoughts on how I can trouble shoot this really welcome. 

1. Copy bom-weather-card via HACS and then install in HA.
2. Install average sensor via HACS (no need to install in HA apparently).
3. Copy directory bom_icons to ./www/icons/
4. Copy directories static and animated to /www/icons/weather_icons/
5. Create directory 'packages' and copy weather.yaml into it, replacing gosford and kariong as required.
6. Edit configuration.yaml to have the following
`  homeassistant:`
     `         packages: !include_dir_named packages`
7. Copy lovelace.yaml into HA root and replace gosford and kariong as required.
8. Go to your home dashboard and edit it, add card and choose bom weather card.
9. In this UI is where you enter the following at the top:
`  type: 'custom:bom-weather-card'`
`resources:`
`  - url: /hacsfiles/bom-weather-card/bom-weather-card.js`
`    type: module`
(if you didn't do a hacs install, the url is slightly different).
10. Paste the text from template.md in below that

![2020-12-23-130113_1280x720_scrot](https://user-images.githubusercontent.com/75926367/102950551-f95eb100-451e-11eb-8c19-09455d72ab81.png)
![2020-12-23-130008_1280x720_scrot](https://user-images.githubusercontent.com/75926367/102950480-dfbd6980-451e-11eb-8878-b552959eb1ac.png)
, replacing gosford and kariong as required.

**Comment by DavidFW1960** [comment]
Can you show your Lovelace config and your edited package. Don’t post screenshots post the code. As always the issue will be you parsing an entity to the card that doesn’t exist.

**Comment by itsslamdunx** [comment]
Thanks mate got there in the end. It's really awesome.The trick is to go into lovelace's raw configuration editor and add all the sensors you're using as individual 'entity:' items up the top. That way the page will load and you'll quickly see what's not a thing because it'll be marked in red.In this case it was kilometer misspelled like that for wind and gusts. I guess I grabbed that text from one of the git how to pages.Again, a clear, numbered step by step install guide would really help users, rather than pictures of directory structures and guessing which bits you have to put where and might not have included and throwing everything at it to get it to run. Currently the instructions make it seem like if you use hacs it'll just work which isn't the case.For those who follow note that it seems there's no need to put a reference to the resources url anywhere.

    On Wednesday, 23 December 2020, 3:51:02 pm AEDT, DavidFW1960 <notifications@github.com> wrote:  
 
 


Can you show your Lovelace config and your edited package. Don’t post screenshots post the code. As always the issue will be you parsing an entity to the card that doesn’t exist.

**Comment by DavidFW1960** [comment]
Glad you got it going. I do provide an example lovelace file as well as a package. If you do a search and replace in those files it will just work and you copy/paste out of the lovelace yaml file when you create the card.

I show the directory structures because people do tend to not follow the instructions and then don't see any icons.

If you think the docs can be improved you can submit a PR for the docs. Whenever someone has a generic error with the docs I do look to see if I can make changes to make things clearer.

**Comment by itsslamdunx** [comment]
Thanks David. Really appreciate your work on a fabulous contribution to the community.

    On Wednesday, 23 December 2020, 5:45:21 pm AEDT, DavidFW1960 <notifications@github.com> wrote:  
 
 


Glad you got it going. I do provide an example lovelace file as well as a package. If you do a search and replace in those files it will just work and you copy/paste out of the lovelace yaml file when you create the card.

I show the directory structures because people do tend to not follow the instructions and then don't see any icons.

If you think the docs can be improved you can submit a PR for the docs. Whenever someone has a generic error with the docs I do look to see if I can make changes to make things clearer.
