### ISSUE TITLE
Since upgrading Home Assistant to 2021.6.1 Weather Card No Longer Works

### ISSUE THREAD

**Issue by miljw002** [DavidFW1960/bom-weather-card#53]
Hi,

I've recently updated to 2021.6.1 and then 2021.6.2, and the weather card no longer works.

If I look in the system log I see the following error:

Logger: frontend.js.latest.202106030
Source: components/system_log/__init__.py:190 
First occurred: 10:30:19 PM (5 occurrences) 
Last logged: 10:31:56 PM

https://hass/local/custom_ui/bom-weather-card.js?v=0.1:891:13 TypeError: null is not an object (evaluating 'root.childElementCount')

Any suggestions welcome.

James

**Comment by DavidFW1960** [comment]
0.89a specifically addresses this issue since before 2021.6.x was released. Please update and make sure you open Chrome Dev Tools, right click the refresh button and select Empty Cache & Hard Reload. 
![image](https://user-images.githubusercontent.com/36390762/120908648-a41ef200-c6af-11eb-8939-7315bb047684.png)
Then CTRL+R a few times. You should then see 0.89c in the console in chrome.
![image](https://user-images.githubusercontent.com/36390762/120908652-b26d0e00-c6af-11eb-8aa8-4ea13b7a16a8.png)
